/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "JwtAccessSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "JwtRefreshSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TimeMgmrTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "VapidPrivateKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "VapidPublicKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}

import "sst"
export {}